SectionVerb {
	EnableSequence [
		cset "name='TERT_TDM_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='aw882xx_mode_switch_l' 0"
		cset "name='aw882xx_mode_switch_r' 0"
		cset "name='aw882xx_pa_switch_l' 0"
		cset "name='aw882xx_pa_switch_r' 0"
	]

	DisableSequence [
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker"

	EnableSequence [
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 100
		PlaybackChannels 2
		PlaybackPCM "hw:meizum2172sndca,0" # MultiMedia1
	}
}
