LibraryConfig.pcm.SubstiConfig {
	pcm.m2172_bottom {
		type route
		slave {
			pcm {
				type hw
				card "${CardId}"
				device 0
			}
			channels 2
		}
		ttable.0.0 1
	}

	pcm.m2172_top {
		type route
		slave {
			pcm {
				type hw
				card "${CardId}"
				device 0
			}
			channels 2
		}
		ttable.0.1 1
	}

	pcm.m2172_stereo {
		type route
		slave {
			pcm {
				type hw
				card "${CardId}"
				device 0
			}
			channels 2
		}
		ttable.0.0 1
		ttable.1.1 1
	}
}

SectionVerb {
	EnableSequence [
		cset "name='TERT_TDM_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='aw882xx_mode_switch_l' 0"
		cset "name='aw882xx_mode_switch_r' 0"
		cset "name='aw882xx_pa_switch_l' 1"
		cset "name='aw882xx_pa_switch_r' 1"
	]

	DisableSequence [
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Bottom Speaker"

	ConflictingDevice [
		"Earpiece"
		"StereoSpeaker"
	]

	EnableSequence [
		cset "name='aw882xx_pa_switch_l' 0"
		cset "name='aw882xx_pa_switch_r' 1"
	]

	DisableSequence [
		cset "name='aw882xx_pa_switch_l' 1"
	]

	Value {
		PlaybackPriority 300
		PlaybackChannels 1
		PlaybackPCM "m2172_bottom"
	}
}

SectionDevice."Earpiece" {
	Comment "Top Speaker"

	ConflictingDevice [
		"Speaker"
		"StereoSpeaker"
	]

	EnableSequence [
		cset "name='aw882xx_pa_switch_l' 1"
		cset "name='aw882xx_pa_switch_r' 0"
	]

	DisableSequence [
		cset "name='aw882xx_pa_switch_r' 1"
	]

	Value {
		PlaybackPriority 200
		PlaybackChannels 1
		PlaybackPCM "m2172_top"
	}
}

SectionDevice."StereoSpeaker" {
	Comment "Stereo Speakers"

	ConflictingDevice [
		"Speaker"
		"Earpiece"
	]

	EnableSequence [
		cset "name='aw882xx_pa_switch_l' 0"
		cset "name='aw882xx_pa_switch_r' 0"
	]

	DisableSequence [
		cset "name='aw882xx_pa_switch_l' 1"
		cset "name='aw882xx_pa_switch_r' 1"
	]

	Value {
		PlaybackPriority 100
		PlaybackChannels 2
		PlaybackPCM "m2172_stereo"
	}
}
