LibraryConfig.pcm.SubstiConfig.pcm."m2172_bottom" {
	@args [ CARD DEV ]
	@args {
		CARD.type string
		DEV.type integer
	}
	type route
	slave {
		pcm {
			type hw
			card $CARD
			device $DEV
		}
		channels 2
		format S16_LE
	}
	ttable.0.0 0.5
	ttable.1.0 0.5
}

SectionVerb {
	EnableSequence [
		cset "name='TERT_TDM_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia2 Mixer VA_CODEC_DMA_TX_0' 1"
		cset "name='aw882xx_mode_switch_l' 0"
		cset "name='aw882xx_mode_switch_r' 0"
		cset "name='aw882xx_pa_switch_l' 0"
		cset "name='aw882xx_pa_switch_r' 1"
	]

	DisableSequence [
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia2 Mixer VA_CODEC_DMA_TX_0' 0"
		cset "name='aw882xx_pa_switch_l' 1"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Bottom Speaker"

	Value {
		PlaybackPriority 300
		PlaybackChannels 2
		PlaybackPCM "m2172_bottom:${CardId},0"
		PlaybackChannel0 0
		PlaybackChannelPos0 FL
		PlaybackChannel1 1
		PlaybackChannelPos1 FR
	}
}

SectionDevice."Mic" {
	Comment "Bottom Microphone"

	Include.lpassva0e.File "/codecs/qcom-lpass/va-macro/DMIC0EnableSeq.conf"
	Include.lpassva0d.File "/codecs/qcom-lpass/va-macro/DMIC0DisableSeq.conf"
	Include.lpassva1e.File "/codecs/qcom-lpass/va-macro/DMIC1EnableSeq.conf"
	Include.lpassva1d.File "/codecs/qcom-lpass/va-macro/DMIC1DisableSeq.conf"

	Value {
		CapturePriority 100
		CaptureChannels 2
		CapturePCM "hw:${CardId},1"
		CaptureChannel0 0
		CaptureChannelPos0 FL
		CaptureChannel1 1
		CaptureChannelPos1 FR
	}
}
