SectionVerb {
	EnableSequence [
		cset "name='TERT_TDM_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='aw882xx_mode_switch_l' 0"
		cset "name='aw882xx_mode_switch_r' 0"
		cset "name='aw882xx_pa_switch_l' 0"
		cset "name='aw882xx_pa_switch_r' 0"
	]

	DisableSequence [
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='aw882xx_pa_switch_l' 1"
		cset "name='aw882xx_pa_switch_r' 1"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."StereoSpeaker" {
	Comment "Stereo Speakers"

	Value {
		PlaybackPriority 100
		PlaybackChannels 2
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannel0 0
		PlaybackChannelPos0 FL
		PlaybackChannel1 1
		PlaybackChannelPos1 FR
	}
}
